### ISSUE TITLE
Add the ability to preview apps for each PR

### ISSUE THREAD

**Issue by taras** [resideo-platform/exemplar#25]
**Is your feature request related to a problem?**

We don't currently have any way for designers to see the result of a PR without having the entire development environment setup locally.

**Describe the solution you'd like**

It would be helpful to see the latest commit in the PR as a runnable app.

**Comment by cowboyd** [comment]
Check out http://fabric.io/blog/fastlane-updates-powerful-prs-enhanced-deployment/ for a great implementation of this.
